const SUPERADMIN = "SUPERADMIN";
const ADMIN = "ADMIN";
const INSTRUCTOR = "INSTRUCTOR";
const USER = "USER";
const PENDING = "PENDING";
const ACCEPTED = "ACCEPTED";
const REJECTED = "REJECTED";

export { SUPERADMIN, ADMIN, INSTRUCTOR, USER, PENDING, ACCEPTED, REJECTED }